import { StyleSheet } from 'react-native';

const globalStyles = StyleSheet.create({
  cancelButton: {
    color: '#407AFF',
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 16,
  },
  containerSearch: {
    alignItems: 'center',
    borderColor: '#DADADA',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
  },
  flagSafeArea: {
    flex: 1,
    padding: 28,
    backgroundColor: '#ffffff',
  },
  flagViewContainer: { flexDirection: 'row', width: '100%' },
  flexRow: { flexDirection: 'row' },
  login: {
    alignSelf: 'center',
    color: '#407AFF',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 16,
    marginStart: 4,
  },
  marginEndIconTextInput: { marginEnd: 16 },
  marginStartIconTextInput: { marginStart: 16 },
  radioActive: {
    backgroundColor: '#407AFF',
    borderColor: '#407AFF',
    borderWidth: 1,
    borderRadius: 16,
    height: 16,
    width: 16,
  },
  radioInActive: {
    backgroundColor: '#ffffff',
    borderColor: '#407AFF',
    borderWidth: 1,
    borderRadius: 16,
    height: 16,
    width: 16,
  },
  registerSafeArea: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 28,
    backgroundColor: '#ffffff',
  },
  selectCountryTitle: {
    color: '#323232',
    flex: 1,
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 22,
    textAlign: 'center',
  },
  subtitleRegister: {
    color: '#87898E',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 17,
    paddingHorizontal: 8,
    paddingTop: 16,
    textAlign: 'center',
  },
  textButton: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 16,
    padding: 16,
    width: '100%',
    textAlign: 'center',
  },
  textDescLogin: {
    alignSelf: 'center',
    color: '#87898E',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 16,
  },
  textInput: {
    color: '#87898E',
    flex: 1,
    padding: 8,
  },
  titleRegister: {
    color: '#000000',
    fontSize: 24,
    fontWeight: '600',
  },
  viewButton: { backgroundColor: '#407AFF', borderRadius: 23, width: '100%' },
  viewFlags: {
    flex: 1,
    flexDirection: 'row',
    paddingVertical: 8,
    alignItems: 'center',
  },
  viewTextInputRegister: {
    alignItems: 'center',
    borderColor: '#DADADA',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
  },
  viewTitleFlag: {
    color: '#737478',
    fontSize: 13,
    fontWeight: '400',
    lineHeight: 16,
  },
});

export default globalStyles;
